# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Designer/cadastro_ok.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_cadastro_ok(object):
    def setupUi(self, cadastro_ok):
        cadastro_ok.setObjectName("cadastro_ok")
        cadastro_ok.resize(356, 103)
        self.gridLayout = QtWidgets.QGridLayout(cadastro_ok)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(cadastro_ok)
        self.frame.setMinimumSize(QtCore.QSize(334, 81))
        self.frame.setStyleSheet("border-radius: 7px;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.Button_quit = QtWidgets.QPushButton(self.frame)
        self.Button_quit.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setBold(True)
        font.setWeight(75)
        self.Button_quit.setFont(font)
        self.Button_quit.setStyleSheet("QPushButton{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgb(0, 0, 41), stop:1 rgb(34, 18, 127));\n"
"    color:rgba(255, 255, 255, 210);\n"
"    border-radius:5px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgb(17, 9, 84), stop:1 rgb(67, 36, 212));\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgb(34, 18, 127), stop:1 rgb(0, 0, 41));\n"
"}")
        self.Button_quit.setObjectName("Button_quit")
        self.gridLayout_2.addWidget(self.Button_quit, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)

        self.retranslateUi(cadastro_ok)
        QtCore.QMetaObject.connectSlotsByName(cadastro_ok)

    def retranslateUi(self, cadastro_ok):
        _translate = QtCore.QCoreApplication.translate
        cadastro_ok.setWindowTitle(_translate("cadastro_ok", "Form"))
        self.label.setText(_translate("cadastro_ok", "Usuário cadastrado com sucesso."))
        self.Button_quit.setText(_translate("cadastro_ok", "OK"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    cadastro_ok = QtWidgets.QWidget()
    ui = Ui_cadastro_ok()
    ui.setupUi(cadastro_ok)
    cadastro_ok.show()
    sys.exit(app.exec_())
