# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Designer/Calendar.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Calendario(object):
    def setupUi(self, Calendario):
        Calendario.setObjectName("Calendario")
        Calendario.resize(363, 256)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Designer\\calendar_icon.webp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Calendario.setWindowIcon(icon)
        self.calendar = QtWidgets.QCalendarWidget(Calendario)
        self.calendar.setGeometry(QtCore.QRect(11, 11, 343, 236))
        self.calendar.setVerticalHeaderFormat(QtWidgets.QCalendarWidget.NoVerticalHeader)
        self.calendar.setObjectName("calendar")

        self.retranslateUi(Calendario)
        QtCore.QMetaObject.connectSlotsByName(Calendario)

    def retranslateUi(self, Calendario):
        _translate = QtCore.QCoreApplication.translate
        Calendario.setWindowTitle(_translate("Calendario", "Calendario"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Calendario = QtWidgets.QWidget()
    ui = Ui_Calendario()
    ui.setupUi(Calendario)
    Calendario.show()
    sys.exit(app.exec_())
