# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Designer/login.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Login(object):
    def setupUi(self, Login):
        Login.setObjectName("Login")
        Login.resize(240, 430)
        Login.setMinimumSize(QtCore.QSize(240, 430))
        Login.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        Login.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Designer\\Logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Login.setWindowIcon(icon)
        Login.setStyleSheet("")
        self.widget = QtWidgets.QWidget(Login)
        self.widget.setGeometry(QtCore.QRect(9, 9, 222, 412))
        self.widget.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 5px;")
        self.widget.setObjectName("widget")
        self.input_user = QtWidgets.QLineEdit(self.widget)
        self.input_user.setGeometry(QtCore.QRect(20, 140, 190, 40))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(10)
        self.input_user.setFont(font)
        self.input_user.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border:none;\n"
"border-bottom:2px solid rgb(67, 36, 212);\n"
"color:rgba(0, 0, 0, 240);\n"
"padding-bottom:7px;")
        self.input_user.setObjectName("input_user")
        self.input_password = QtWidgets.QLineEdit(self.widget)
        self.input_password.setGeometry(QtCore.QRect(20, 210, 190, 40))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(10)
        self.input_password.setFont(font)
        self.input_password.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border:none;\n"
"border-bottom:2px solid rgb(67, 36, 212);\n"
"color:rgba(0, 0, 0, 240);\n"
"padding-bottom:7px;")
        self.input_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.input_password.setObjectName("input_password")
        self.title_login = QtWidgets.QLabel(self.widget)
        self.title_login.setGeometry(QtCore.QRect(60, 60, 111, 40))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.title_login.setFont(font)
        self.title_login.setStyleSheet("color:rgba(0, 0, 0, 200);")
        self.title_login.setObjectName("title_login")
        self.forgot_password = QtWidgets.QLabel(self.widget)
        self.forgot_password.setGeometry(QtCore.QRect(26, 325, 181, 16))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        self.forgot_password.setFont(font)
        self.forgot_password.setStyleSheet("color:rgba(0, 0, 0, 210);")
        self.forgot_password.setObjectName("forgot_password")
        self.button_login = QtWidgets.QPushButton(self.widget)
        self.button_login.setGeometry(QtCore.QRect(20, 275, 190, 40))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.button_login.setFont(font)
        self.button_login.setStyleSheet("QPushButton{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgb(0, 0, 41), stop:1 rgb(34, 18, 127));\n"
"    color:rgba(255, 255, 255, 210);\n"
"    border-radius:5px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgb(17, 9, 84), stop:1 rgb(67, 36, 212));\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgb(34, 18, 127), stop:1 rgb(0, 0, 41));\n"
"}")
        self.button_login.setObjectName("button_login")

        self.retranslateUi(Login)
        QtCore.QMetaObject.connectSlotsByName(Login)

    def retranslateUi(self, Login):
        _translate = QtCore.QCoreApplication.translate
        Login.setWindowTitle(_translate("Login", "Login"))
        self.input_user.setPlaceholderText(_translate("Login", "  Usuário"))
        self.input_password.setPlaceholderText(_translate("Login", "  Senha"))
        self.title_login.setText(_translate("Login", "Login"))
        self.forgot_password.setText(_translate("Login", "Esqueceu sua Senha?"))
        self.button_login.setText(_translate("Login", "Login"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Login = QtWidgets.QWidget()
    ui = Ui_Login()
    ui.setupUi(Login)
    Login.show()
    sys.exit(app.exec_())
