# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Designer/pesquisa_usuarios.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_pesquisa_perfil(object):
    def setupUi(self, pesquisa_perfil):
        pesquisa_perfil.setObjectName("pesquisa_perfil")
        pesquisa_perfil.setWindowModality(QtCore.Qt.NonModal)
        pesquisa_perfil.resize(900, 520)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(pesquisa_perfil.sizePolicy().hasHeightForWidth())
        pesquisa_perfil.setSizePolicy(sizePolicy)
        pesquisa_perfil.setMinimumSize(QtCore.QSize(900, 520))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Designer\\Logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        pesquisa_perfil.setWindowIcon(icon)
        self.gridLayout = QtWidgets.QGridLayout(pesquisa_perfil)
        self.gridLayout.setObjectName("gridLayout")
        self.pesquisa_usuarios = QtWidgets.QTableWidget(pesquisa_perfil)
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(8)
        self.pesquisa_usuarios.setFont(font)
        self.pesquisa_usuarios.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.pesquisa_usuarios.setFrameShadow(QtWidgets.QFrame.Plain)
        self.pesquisa_usuarios.setLineWidth(1)
        self.pesquisa_usuarios.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.pesquisa_usuarios.setEditTriggers(QtWidgets.QAbstractItemView.AnyKeyPressed|QtWidgets.QAbstractItemView.DoubleClicked|QtWidgets.QAbstractItemView.EditKeyPressed|QtWidgets.QAbstractItemView.SelectedClicked)
        self.pesquisa_usuarios.setDragEnabled(False)
        self.pesquisa_usuarios.setShowGrid(True)
        self.pesquisa_usuarios.setGridStyle(QtCore.Qt.SolidLine)
        self.pesquisa_usuarios.setWordWrap(True)
        self.pesquisa_usuarios.setCornerButtonEnabled(True)
        self.pesquisa_usuarios.setObjectName("pesquisa_usuarios")
        self.pesquisa_usuarios.setColumnCount(6)
        self.pesquisa_usuarios.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.pesquisa_usuarios.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.pesquisa_usuarios.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.pesquisa_usuarios.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.pesquisa_usuarios.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.pesquisa_usuarios.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.pesquisa_usuarios.setHorizontalHeaderItem(5, item)
        self.pesquisa_usuarios.horizontalHeader().setCascadingSectionResizes(False)
        self.gridLayout.addWidget(self.pesquisa_usuarios, 0, 0, 1, 1)

        self.retranslateUi(pesquisa_perfil)
        QtCore.QMetaObject.connectSlotsByName(pesquisa_perfil)

    def retranslateUi(self, pesquisa_perfil):
        _translate = QtCore.QCoreApplication.translate
        pesquisa_perfil.setWindowTitle(_translate("pesquisa_perfil", "Pesquisa Perfil"))
        self.pesquisa_usuarios.setSortingEnabled(False)
        item = self.pesquisa_usuarios.horizontalHeaderItem(0)
        item.setText(_translate("pesquisa_perfil", "nome_pessoa"))
        item = self.pesquisa_usuarios.horizontalHeaderItem(1)
        item.setText(_translate("pesquisa_perfil", "data_nascimento"))
        item = self.pesquisa_usuarios.horizontalHeaderItem(2)
        item.setText(_translate("pesquisa_perfil", "sexo"))
        item = self.pesquisa_usuarios.horizontalHeaderItem(3)
        item.setText(_translate("pesquisa_perfil", "email"))
        item = self.pesquisa_usuarios.horizontalHeaderItem(4)
        item.setText(_translate("pesquisa_perfil", "telefone"))
        item = self.pesquisa_usuarios.horizontalHeaderItem(5)
        item.setText(_translate("pesquisa_perfil", "endereco"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    pesquisa_perfil = QtWidgets.QWidget()
    ui = Ui_pesquisa_perfil()
    ui.setupUi(pesquisa_perfil)
    pesquisa_perfil.show()
    sys.exit(app.exec_())
