# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Designer/register.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Register(object):
    def setupUi(self, Register):
        Register.setObjectName("Register")
        Register.resize(530, 440)
        Register.setMinimumSize(QtCore.QSize(530, 440))
        Register.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        Register.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Designer\\Logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Register.setWindowIcon(icon)
        Register.setStyleSheet("")
        self.widget = QtWidgets.QWidget(Register)
        self.widget.setGeometry(QtCore.QRect(11, 11, 508, 418))
        self.widget.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 5px;")
        self.widget.setObjectName("widget")
        self.title_register = QtWidgets.QLabel(self.widget)
        self.title_register.setGeometry(QtCore.QRect(0, 20, 511, 61))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.title_register.setFont(font)
        self.title_register.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.title_register.setStyleSheet("color:rgba(0, 0, 0, 200);")
        self.title_register.setAlignment(QtCore.Qt.AlignCenter)
        self.title_register.setObjectName("title_register")
        self.button_register = QtWidgets.QPushButton(self.widget)
        self.button_register.setGeometry(QtCore.QRect(270, 360, 230, 40))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.button_register.setFont(font)
        self.button_register.setStyleSheet("QPushButton{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgb(0, 0, 41), stop:1 rgb(34, 18, 127));\n"
"    color:rgba(255, 255, 255, 210);\n"
"    border-radius:5px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgb(17, 9, 84), stop:1 rgb(67, 36, 212));\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgb(34, 18, 127), stop:1 rgb(0, 0, 41));\n"
"}")
        self.button_register.setObjectName("button_register")
        self.input_password_confirme = QtWidgets.QLineEdit(self.widget)
        self.input_password_confirme.setGeometry(QtCore.QRect(10, 360, 230, 40))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(10)
        self.input_password_confirme.setFont(font)
        self.input_password_confirme.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border:none;\n"
"border-bottom:2px solid rgb(67, 36, 212);\n"
"color:rgba(0, 0, 0, 240);\n"
"padding-bottom:7px;")
        self.input_password_confirme.setFrame(True)
        self.input_password_confirme.setEchoMode(QtWidgets.QLineEdit.Password)
        self.input_password_confirme.setObjectName("input_password_confirme")
        self.input_password = QtWidgets.QLineEdit(self.widget)
        self.input_password.setGeometry(QtCore.QRect(10, 300, 230, 40))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(10)
        self.input_password.setFont(font)
        self.input_password.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border:none;\n"
"border-bottom:2px solid rgb(67, 36, 212);\n"
"color:rgba(0, 0, 0, 240);\n"
"padding-bottom:7px;")
        self.input_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.input_password.setObjectName("input_password")
        self.input_email = QtWidgets.QLineEdit(self.widget)
        self.input_email.setGeometry(QtCore.QRect(270, 300, 230, 40))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(10)
        self.input_email.setFont(font)
        self.input_email.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border:none;\n"
"border-bottom:2px solid rgb(67, 36, 212);\n"
"color:rgba(0, 0, 0, 240);\n"
"padding-bottom:7px;")
        self.input_email.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.input_email.setObjectName("input_email")
        self.input_adress = QtWidgets.QLineEdit(self.widget)
        self.input_adress.setGeometry(QtCore.QRect(270, 240, 230, 40))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(10)
        self.input_adress.setFont(font)
        self.input_adress.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border:none;\n"
"border-bottom:2px solid rgb(67, 36, 212);\n"
"color:rgba(0, 0, 0, 240);\n"
"padding-bottom:7px;")
        self.input_adress.setEchoMode(QtWidgets.QLineEdit.Password)
        self.input_adress.setObjectName("input_adress")
        self.input_phone = QtWidgets.QLineEdit(self.widget)
        self.input_phone.setGeometry(QtCore.QRect(270, 180, 230, 40))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(10)
        self.input_phone.setFont(font)
        self.input_phone.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border:none;\n"
"border-bottom:2px solid rgb(67, 36, 212);\n"
"color:rgba(0, 0, 0, 240);\n"
"padding-bottom:7px;")
        self.input_phone.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.input_phone.setObjectName("input_phone")
        self.input_name = QtWidgets.QLineEdit(self.widget)
        self.input_name.setGeometry(QtCore.QRect(10, 120, 230, 40))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(10)
        self.input_name.setFont(font)
        self.input_name.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border:none;\n"
"border-bottom:2px solid rgb(67, 36, 212);\n"
"color:rgba(0, 0, 0, 240);\n"
"padding-bottom:7px;")
        self.input_name.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.input_name.setObjectName("input_name")
        self.input_cpf = QtWidgets.QLineEdit(self.widget)
        self.input_cpf.setGeometry(QtCore.QRect(10, 180, 230, 40))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(10)
        self.input_cpf.setFont(font)
        self.input_cpf.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border:none;\n"
"border-bottom:2px solid rgb(67, 36, 212);\n"
"color:rgba(0, 0, 0, 240);\n"
"padding-bottom:7px;")
        self.input_cpf.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.input_cpf.setObjectName("input_cpf")
        self.input_sexo = QtWidgets.QLineEdit(self.widget)
        self.input_sexo.setGeometry(QtCore.QRect(10, 240, 230, 40))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(10)
        self.input_sexo.setFont(font)
        self.input_sexo.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border:none;\n"
"border-bottom:2px solid rgb(67, 36, 212);\n"
"color:rgba(0, 0, 0, 240);\n"
"padding-bottom:7px;")
        self.input_sexo.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.input_sexo.setObjectName("input_sexo")
        self.input_data = QtWidgets.QDateEdit(self.widget)
        self.input_data.setGeometry(QtCore.QRect(270, 120, 230, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.input_data.sizePolicy().hasHeightForWidth())
        self.input_data.setSizePolicy(sizePolicy)
        self.input_data.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.input_data.setFont(font)
        self.input_data.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.input_data.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border:none;\n"
"border-bottom:2px solid rgb(67, 36, 212);\n"
"color:rgba(0, 0, 0, 140);\n"
"padding-bottom:7px;")
        self.input_data.setAlignment(QtCore.Qt.AlignCenter)
        self.input_data.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.input_data.setObjectName("input_data")
        self.button_calendar = QtWidgets.QPushButton(self.widget)
        self.button_calendar.setGeometry(QtCore.QRect(460, 120, 40, 40))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(2)
        self.button_calendar.setFont(font)
        self.button_calendar.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border:none;\n"
"color:rgba(0, 0, 0, 240);\n"
"")
        self.button_calendar.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Designer\\calendar_icon.webp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_calendar.setIcon(icon1)
        self.button_calendar.setObjectName("button_calendar")
        self.title_register.raise_()
        self.button_register.raise_()
        self.input_password_confirme.raise_()
        self.input_password.raise_()
        self.input_email.raise_()
        self.input_phone.raise_()
        self.input_name.raise_()
        self.input_adress.raise_()
        self.input_cpf.raise_()
        self.input_sexo.raise_()
        self.input_data.raise_()
        self.button_calendar.raise_()

        self.retranslateUi(Register)
        QtCore.QMetaObject.connectSlotsByName(Register)

    def retranslateUi(self, Register):
        _translate = QtCore.QCoreApplication.translate
        Register.setWindowTitle(_translate("Register", "Registrar"))
        self.title_register.setText(_translate("Register", "Registrar"))
        self.button_register.setText(_translate("Register", "Registrar"))
        self.input_password_confirme.setPlaceholderText(_translate("Register", "  Confirmar Senha"))
        self.input_password.setPlaceholderText(_translate("Register", "  Senha"))
        self.input_email.setPlaceholderText(_translate("Register", "  Email"))
        self.input_adress.setPlaceholderText(_translate("Register", "  Endereço"))
        self.input_phone.setPlaceholderText(_translate("Register", "  Celular"))
        self.input_name.setPlaceholderText(_translate("Register", "  Nome"))
        self.input_cpf.setPlaceholderText(_translate("Register", "  CPF"))
        self.input_sexo.setPlaceholderText(_translate("Register", "  Sexo"))
        self.input_data.setDisplayFormat(_translate("Register", "dd/MM/yyyy"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Register = QtWidgets.QWidget()
    ui = Ui_Register()
    ui.setupUi(Register)
    Register.show()
    sys.exit(app.exec_())
