# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Designer/widget_main.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Sistema_de_Agendamento_Psicologico(object):
    def setupUi(self, Sistema_de_Agendamento_Psicologico):
        Sistema_de_Agendamento_Psicologico.setObjectName("Sistema_de_Agendamento_Psicologico")
        Sistema_de_Agendamento_Psicologico.resize(1080, 720)
        Sistema_de_Agendamento_Psicologico.setMinimumSize(QtCore.QSize(1080, 720))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Designer\\Logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Sistema_de_Agendamento_Psicologico.setWindowIcon(icon)
        Sistema_de_Agendamento_Psicologico.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.horizontalLayout = QtWidgets.QHBoxLayout(Sistema_de_Agendamento_Psicologico)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Sidebar = QtWidgets.QFrame(Sistema_de_Agendamento_Psicologico)
        self.Sidebar.setMinimumSize(QtCore.QSize(120, 720))
        self.Sidebar.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.Sidebar.setStyleSheet("background-color: rgb(50, 27, 170, 0);")
        self.Sidebar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Sidebar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Sidebar.setObjectName("Sidebar")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.Sidebar)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Button_main_page = QtWidgets.QPushButton(self.Sidebar)
        self.Button_main_page.setMaximumSize(QtCore.QSize(120, 120))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.Button_main_page.setFont(font)
        self.Button_main_page.setStyleSheet("QPushButton{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgb(0, 0, 41), stop:1 rgb(34, 18, 127));\n"
"    color:rgba(255, 255, 255, 210);\n"
"    border-radius:5px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgb(17, 9, 84), stop:1 rgb(67, 36, 212));\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgb(34, 18, 127), stop:1 rgb(0, 0, 41));\n"
"}")
        self.Button_main_page.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Designer\\icon_home.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Button_main_page.setIcon(icon1)
        self.Button_main_page.setIconSize(QtCore.QSize(70, 70))
        self.Button_main_page.setObjectName("Button_main_page")
        self.verticalLayout.addWidget(self.Button_main_page)
        self.Button_register_page = QtWidgets.QPushButton(self.Sidebar)
        self.Button_register_page.setMaximumSize(QtCore.QSize(120, 120))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setBold(True)
        font.setWeight(75)
        self.Button_register_page.setFont(font)
        self.Button_register_page.setStyleSheet("QPushButton{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgb(0, 0, 41), stop:1 rgb(34, 18, 127));\n"
"    color:rgba(255, 255, 255, 210);\n"
"    border-radius:5px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgb(17, 9, 84), stop:1 rgb(67, 36, 212));\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgb(34, 18, 127), stop:1 rgb(0, 0, 41));\n"
"}")
        self.Button_register_page.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("Designer\\register_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Button_register_page.setIcon(icon2)
        self.Button_register_page.setIconSize(QtCore.QSize(70, 70))
        self.Button_register_page.setObjectName("Button_register_page")
        self.verticalLayout.addWidget(self.Button_register_page)
        self.Button_view_page = QtWidgets.QPushButton(self.Sidebar)
        self.Button_view_page.setMaximumSize(QtCore.QSize(120, 120))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setBold(True)
        font.setWeight(75)
        self.Button_view_page.setFont(font)
        self.Button_view_page.setStyleSheet("QPushButton{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgb(0, 0, 41), stop:1 rgb(34, 18, 127));\n"
"    color:rgba(255, 255, 255, 210);\n"
"    border-radius:5px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgb(17, 9, 84), stop:1 rgb(67, 36, 212));\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgb(34, 18, 127), stop:1 rgb(0, 0, 41));\n"
"}")
        self.Button_view_page.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("Designer\\consulta_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Button_view_page.setIcon(icon3)
        self.Button_view_page.setIconSize(QtCore.QSize(70, 70))
        self.Button_view_page.setObjectName("Button_view_page")
        self.verticalLayout.addWidget(self.Button_view_page)
        self.Button_make_page = QtWidgets.QPushButton(self.Sidebar)
        self.Button_make_page.setMaximumSize(QtCore.QSize(120, 120))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.Button_make_page.setFont(font)
        self.Button_make_page.setStyleSheet("QPushButton{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgb(0, 0, 41), stop:1 rgb(34, 18, 127));\n"
"    color:rgba(255, 255, 255, 210);\n"
"    border-radius:5px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgb(17, 9, 84), stop:1 rgb(67, 36, 212));\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgb(34, 18, 127), stop:1 rgb(0, 0, 41));\n"
"}")
        self.Button_make_page.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("Designer\\make_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Button_make_page.setIcon(icon4)
        self.Button_make_page.setIconSize(QtCore.QSize(70, 70))
        self.Button_make_page.setAutoRepeat(False)
        self.Button_make_page.setObjectName("Button_make_page")
        self.verticalLayout.addWidget(self.Button_make_page)
        self.Logo_Ideau = QtWidgets.QLabel(self.Sidebar)
        self.Logo_Ideau.setMaximumSize(QtCore.QSize(120, 120))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.Logo_Ideau.setFont(font)
        self.Logo_Ideau.setText("")
        self.Logo_Ideau.setPixmap(QtGui.QPixmap("Designer\\Logo_ideau.png"))
        self.Logo_Ideau.setScaledContents(True)
        self.Logo_Ideau.setAlignment(QtCore.Qt.AlignCenter)
        self.Logo_Ideau.setObjectName("Logo_Ideau")
        self.verticalLayout.addWidget(self.Logo_Ideau)
        self.horizontalLayout.addWidget(self.Sidebar)
        self.stackedWidget = QtWidgets.QStackedWidget(Sistema_de_Agendamento_Psicologico)
        self.stackedWidget.setMinimumSize(QtCore.QSize(900, 720))
        self.stackedWidget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_main = QtWidgets.QWidget()
        self.page_main.setMinimumSize(QtCore.QSize(0, 0))
        self.page_main.setObjectName("page_main")
        self.label = QtWidgets.QLabel(self.page_main)
        self.label.setGeometry(QtCore.QRect(11, 11, 960, 720))
        self.label.setMinimumSize(QtCore.QSize(0, 0))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("Designer\\Main Image Sistema.jpg"))
        self.label.setScaledContents(True)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.stackedWidget.addWidget(self.page_main)
        self.page_register = QtWidgets.QWidget()
        self.page_register.setObjectName("page_register")
        self.Logo_Ideau_2 = QtWidgets.QLabel(self.page_register)
        self.Logo_Ideau_2.setGeometry(QtCore.QRect(620, 200, 120, 120))
        self.Logo_Ideau_2.setMinimumSize(QtCore.QSize(120, 120))
        self.Logo_Ideau_2.setMaximumSize(QtCore.QSize(120, 120))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.Logo_Ideau_2.setFont(font)
        self.Logo_Ideau_2.setText("")
        self.Logo_Ideau_2.setPixmap(QtGui.QPixmap("Designer\\Logo_ideau.png"))
        self.Logo_Ideau_2.setScaledContents(True)
        self.Logo_Ideau_2.setAlignment(QtCore.Qt.AlignCenter)
        self.Logo_Ideau_2.setObjectName("Logo_Ideau_2")
        self.input_phone = QtWidgets.QLineEdit(self.page_register)
        self.input_phone.setGeometry(QtCore.QRect(100, 500, 300, 60))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(10)
        self.input_phone.setFont(font)
        self.input_phone.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border:none;\n"
"border-bottom:4px solid rgb(67, 36, 212);\n"
"color:rgba(0, 0, 0, 240);\n"
"padding-bottom:7px;")
        self.input_phone.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.input_phone.setObjectName("input_phone")
        self.input_password_confirme = QtWidgets.QLineEdit(self.page_register)
        self.input_password_confirme.setGeometry(QtCore.QRect(530, 500, 300, 60))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(10)
        self.input_password_confirme.setFont(font)
        self.input_password_confirme.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border:none;\n"
"border-bottom:4px solid rgb(67, 36, 212);\n"
"color:rgba(0, 0, 0, 240);\n"
"padding-bottom:7px;")
        self.input_password_confirme.setFrame(True)
        self.input_password_confirme.setEchoMode(QtWidgets.QLineEdit.Password)
        self.input_password_confirme.setObjectName("input_password_confirme")
        self.input_sexo = QtWidgets.QLineEdit(self.page_register)
        self.input_sexo.setGeometry(QtCore.QRect(100, 580, 300, 60))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(10)
        self.input_sexo.setFont(font)
        self.input_sexo.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border:none;\n"
"border-bottom:4px solid rgb(67, 36, 212);\n"
"color:rgba(0, 0, 0, 240);\n"
"padding-bottom:7px;")
        self.input_sexo.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.input_sexo.setObjectName("input_sexo")
        self.input_data = QtWidgets.QDateEdit(self.page_register)
        self.input_data.setGeometry(QtCore.QRect(100, 260, 300, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.input_data.sizePolicy().hasHeightForWidth())
        self.input_data.setSizePolicy(sizePolicy)
        self.input_data.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.input_data.setFont(font)
        self.input_data.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.input_data.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border:none;\n"
"border-bottom:4px solid rgb(67, 36, 212);\n"
"color:rgba(0, 0, 0, 240);\n"
"padding-bottom:7px;")
        self.input_data.setAlignment(QtCore.Qt.AlignCenter)
        self.input_data.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.input_data.setObjectName("input_data")
        self.input_adress = QtWidgets.QLineEdit(self.page_register)
        self.input_adress.setGeometry(QtCore.QRect(100, 420, 300, 60))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(10)
        self.input_adress.setFont(font)
        self.input_adress.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border:none;\n"
"border-bottom:4px solid rgb(67, 36, 212);\n"
"color:rgba(0, 0, 0, 240);\n"
"padding-bottom:7px;")
        self.input_adress.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.input_adress.setObjectName("input_adress")
        self.button_calendar = QtWidgets.QPushButton(self.page_register)
        self.button_calendar.setGeometry(QtCore.QRect(340, 260, 60, 60))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(2)
        self.button_calendar.setFont(font)
        self.button_calendar.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border:none;\n"
"color:rgba(0, 0, 0, 240);\n"
"")
        self.button_calendar.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("Designer\\calendar_icon.webp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_calendar.setIcon(icon5)
        self.button_calendar.setObjectName("button_calendar")
        self.title_register = QtWidgets.QLabel(self.page_register)
        self.title_register.setGeometry(QtCore.QRect(0, 0, 931, 120))
        self.title_register.setMinimumSize(QtCore.QSize(0, 0))
        self.title_register.setMaximumSize(QtCore.QSize(931, 120))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.title_register.setFont(font)
        self.title_register.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.title_register.setStyleSheet("color:rgba(0, 0, 0, 200);\n"
"background-color: rgba(255, 255, 255, 0);")
        self.title_register.setAlignment(QtCore.Qt.AlignCenter)
        self.title_register.setObjectName("title_register")
        self.input_name = QtWidgets.QLineEdit(self.page_register)
        self.input_name.setGeometry(QtCore.QRect(100, 180, 300, 60))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(10)
        self.input_name.setFont(font)
        self.input_name.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border:none;\n"
"border-bottom:4px solid rgb(67, 36, 212);\n"
"color:rgba(0, 0, 0, 240);\n"
"padding-bottom:7px;")
        self.input_name.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.input_name.setObjectName("input_name")
        self.button_register = QtWidgets.QPushButton(self.page_register)
        self.button_register.setGeometry(QtCore.QRect(530, 580, 301, 60))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.button_register.setFont(font)
        self.button_register.setStyleSheet("QPushButton{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgb(0, 0, 41), stop:1 rgb(34, 18, 127));\n"
"    color:rgba(255, 255, 255, 210);\n"
"    border-radius:5px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgb(17, 9, 84), stop:1 rgb(67, 36, 212));\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgb(34, 18, 127), stop:1 rgb(0, 0, 41));\n"
"}")
        self.button_register.setObjectName("button_register")
        self.input_cpf = QtWidgets.QLineEdit(self.page_register)
        self.input_cpf.setGeometry(QtCore.QRect(530, 340, 300, 60))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(10)
        self.input_cpf.setFont(font)
        self.input_cpf.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border:none;\n"
"border-bottom:4px solid rgb(67, 36, 212);\n"
"color:rgba(0, 0, 0, 240);\n"
"padding-bottom:7px;")
        self.input_cpf.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.input_cpf.setObjectName("input_cpf")
        self.input_password = QtWidgets.QLineEdit(self.page_register)
        self.input_password.setGeometry(QtCore.QRect(530, 420, 300, 60))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(10)
        self.input_password.setFont(font)
        self.input_password.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border:none;\n"
"border-bottom:4px solid rgb(67, 36, 212);\n"
"color:rgba(0, 0, 0, 240);\n"
"padding-bottom:7px;")
        self.input_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.input_password.setObjectName("input_password")
        self.input_email = QtWidgets.QLineEdit(self.page_register)
        self.input_email.setGeometry(QtCore.QRect(100, 340, 300, 60))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(10)
        self.input_email.setFont(font)
        self.input_email.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border:none;\n"
"border-bottom:4px solid rgb(67, 36, 212);\n"
"color:rgba(0, 0, 0, 240);\n"
"padding-bottom:7px;")
        self.input_email.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.input_email.setObjectName("input_email")
        self.stackedWidget.addWidget(self.page_register)
        self.page_view = QtWidgets.QWidget()
        self.page_view.setObjectName("page_view")
        self.stackedWidget.addWidget(self.page_view)
        self.page_make = QtWidgets.QWidget()
        self.page_make.setObjectName("page_make")
        self.input_data_make = QtWidgets.QDateEdit(self.page_make)
        self.input_data_make.setGeometry(QtCore.QRect(560, 280, 300, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.input_data_make.sizePolicy().hasHeightForWidth())
        self.input_data_make.setSizePolicy(sizePolicy)
        self.input_data_make.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.input_data_make.setFont(font)
        self.input_data_make.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.input_data_make.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border:none;\n"
"border-bottom:4px solid rgb(67, 36, 212);\n"
"color:rgba(0, 0, 0, 240);\n"
"padding-bottom:7px;")
        self.input_data_make.setAlignment(QtCore.Qt.AlignCenter)
        self.input_data_make.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.input_data_make.setObjectName("input_data_make")
        self.button_calendar_make = QtWidgets.QPushButton(self.page_make)
        self.button_calendar_make.setGeometry(QtCore.QRect(800, 280, 60, 60))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(2)
        self.button_calendar_make.setFont(font)
        self.button_calendar_make.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border:none;\n"
"color:rgba(0, 0, 0, 240);\n"
"")
        self.button_calendar_make.setText("")
        self.button_calendar_make.setIcon(icon5)
        self.button_calendar_make.setObjectName("button_calendar_make")
        self.input_patient = QtWidgets.QLineEdit(self.page_make)
        self.input_patient.setGeometry(QtCore.QRect(70, 280, 300, 60))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(10)
        self.input_patient.setFont(font)
        self.input_patient.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border:none;\n"
"border-bottom:4px solid rgb(67, 36, 212);\n"
"color:rgba(0, 0, 0, 240);\n"
"padding-bottom:7px;")
        self.input_patient.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.input_patient.setObjectName("input_patient")
        self.title_make = QtWidgets.QLabel(self.page_make)
        self.title_make.setGeometry(QtCore.QRect(0, 0, 931, 120))
        self.title_make.setMinimumSize(QtCore.QSize(0, 0))
        self.title_make.setMaximumSize(QtCore.QSize(931, 120))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.title_make.setFont(font)
        self.title_make.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.title_make.setStyleSheet("color:rgba(0, 0, 0, 200);\n"
"background-color: rgba(255, 255, 255, 0);")
        self.title_make.setAlignment(QtCore.Qt.AlignCenter)
        self.title_make.setObjectName("title_make")
        self.input_psychologist = QtWidgets.QLineEdit(self.page_make)
        self.input_psychologist.setGeometry(QtCore.QRect(70, 360, 300, 60))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(10)
        self.input_psychologist.setFont(font)
        self.input_psychologist.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border:none;\n"
"border-bottom:4px solid rgb(67, 36, 212);\n"
"color:rgba(0, 0, 0, 240);\n"
"padding-bottom:7px;")
        self.input_psychologist.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.input_psychologist.setObjectName("input_psychologist")
        self.input_time = QtWidgets.QTimeEdit(self.page_make)
        self.input_time.setGeometry(QtCore.QRect(560, 360, 300, 60))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.input_time.setFont(font)
        self.input_time.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border:none;\n"
"border-bottom:4px solid rgb(67, 36, 212);\n"
"color:rgba(0, 0, 0, 240);\n"
"padding-bottom:7px;")
        self.input_time.setAlignment(QtCore.Qt.AlignCenter)
        self.input_time.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.input_time.setKeyboardTracking(True)
        self.input_time.setObjectName("input_time")
        self.button_make = QtWidgets.QPushButton(self.page_make)
        self.button_make.setGeometry(QtCore.QRect(320, 620, 301, 60))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.button_make.setFont(font)
        self.button_make.setStyleSheet("QPushButton{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgb(0, 0, 41), stop:1 rgb(34, 18, 127));\n"
"    color:rgba(255, 255, 255, 210);\n"
"    border-radius:5px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgb(17, 9, 84), stop:1 rgb(67, 36, 212));\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgb(34, 18, 127), stop:1 rgb(0, 0, 41));\n"
"}")
        self.button_make.setObjectName("button_make")
        self.stackedWidget.addWidget(self.page_make)
        self.horizontalLayout.addWidget(self.stackedWidget)

        self.retranslateUi(Sistema_de_Agendamento_Psicologico)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Sistema_de_Agendamento_Psicologico)

    def retranslateUi(self, Sistema_de_Agendamento_Psicologico):
        _translate = QtCore.QCoreApplication.translate
        Sistema_de_Agendamento_Psicologico.setWindowTitle(_translate("Sistema_de_Agendamento_Psicologico", "Sistema de Agendamento Psicólogico"))
        self.input_phone.setPlaceholderText(_translate("Sistema_de_Agendamento_Psicologico", "  Celular"))
        self.input_password_confirme.setPlaceholderText(_translate("Sistema_de_Agendamento_Psicologico", "  Confirmar Senha"))
        self.input_sexo.setPlaceholderText(_translate("Sistema_de_Agendamento_Psicologico", "  Sexo"))
        self.input_data.setDisplayFormat(_translate("Sistema_de_Agendamento_Psicologico", "dd/MM/yyyy"))
        self.input_adress.setPlaceholderText(_translate("Sistema_de_Agendamento_Psicologico", "  Endereço"))
        self.title_register.setText(_translate("Sistema_de_Agendamento_Psicologico", "Registrar"))
        self.input_name.setPlaceholderText(_translate("Sistema_de_Agendamento_Psicologico", "  Nome"))
        self.button_register.setText(_translate("Sistema_de_Agendamento_Psicologico", "Registrar"))
        self.input_cpf.setPlaceholderText(_translate("Sistema_de_Agendamento_Psicologico", "  CPF"))
        self.input_password.setPlaceholderText(_translate("Sistema_de_Agendamento_Psicologico", "  Senha"))
        self.input_email.setPlaceholderText(_translate("Sistema_de_Agendamento_Psicologico", "  Email"))
        self.input_data_make.setDisplayFormat(_translate("Sistema_de_Agendamento_Psicologico", "dd/MM/yyyy"))
        self.input_patient.setPlaceholderText(_translate("Sistema_de_Agendamento_Psicologico", "  Paciente"))
        self.title_make.setText(_translate("Sistema_de_Agendamento_Psicologico", "Marcar Consulta"))
        self.input_psychologist.setPlaceholderText(_translate("Sistema_de_Agendamento_Psicologico", "  Psicólogo(a)"))
        self.button_make.setText(_translate("Sistema_de_Agendamento_Psicologico", "Marcar Consulta"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Sistema_de_Agendamento_Psicologico = QtWidgets.QWidget()
    ui = Ui_Sistema_de_Agendamento_Psicologico()
    ui.setupUi(Sistema_de_Agendamento_Psicologico)
    Sistema_de_Agendamento_Psicologico.show()
    sys.exit(app.exec_())
